
package fr.afcepf.tp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculTva", targetNamespace = "http://tp.afcepf.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculTva {


    /**
     * 
     * @param taux
     * @param ht
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tva", targetNamespace = "http://tp.afcepf.fr/", className = "fr.afcepf.tp.Tva")
    @ResponseWrapper(localName = "tvaResponse", targetNamespace = "http://tp.afcepf.fr/", className = "fr.afcepf.tp.TvaResponse")
    @Action(input = "http://tp.afcepf.fr/CalculTva/tvaRequest", output = "http://tp.afcepf.fr/CalculTva/tvaResponse")
    public double tva(
        @WebParam(name = "ht", targetNamespace = "")
        double ht,
        @WebParam(name = "taux", targetNamespace = "")
        double taux);

    /**
     * 
     * @param taux
     * @param ht
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ttc", targetNamespace = "http://tp.afcepf.fr/", className = "fr.afcepf.tp.Ttc")
    @ResponseWrapper(localName = "ttcResponse", targetNamespace = "http://tp.afcepf.fr/", className = "fr.afcepf.tp.TtcResponse")
    @Action(input = "http://tp.afcepf.fr/CalculTva/ttcRequest", output = "http://tp.afcepf.fr/CalculTva/ttcResponse")
    public double ttc(
        @WebParam(name = "ht", targetNamespace = "")
        double ht,
        @WebParam(name = "taux", targetNamespace = "")
        double taux);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAuthorName", targetNamespace = "http://tp.afcepf.fr/", className = "fr.afcepf.tp.GetAuthorName")
    @ResponseWrapper(localName = "getAuthorNameResponse", targetNamespace = "http://tp.afcepf.fr/", className = "fr.afcepf.tp.GetAuthorNameResponse")
    @Action(input = "http://tp.afcepf.fr/CalculTva/getAuthorNameRequest", output = "http://tp.afcepf.fr/CalculTva/getAuthorNameResponse")
    public String getAuthorName();

}
